# Название кластера:
cluster.name: my-elasticsearch

# Название узла:
node.name: node-1

# Определяет, на каком интерфейсе слушать входящие запросы:
network.host: 0.0.0.0

# HTTP порт для взаимодействия с REST API:
http.port: 9200

# Отключение обнаружения кластера, полезно для одноузлового кластера:
discovery.type: single-node

# Путь к директории для хранения данных Elasticsearch:
path.data: /var/lib/elasticsearch

# Путь к логам Elasticsearch:
path.logs: /var/log/elasticsearch

# Настройки для Java Virtual Machine (необязательно):
# Эти настройки определяют минимальный (Xms) и максимальный (Xmx) размеры кучи памяти, которые может использовать JVM.
# Рекомендуется установить оба значения равными, чтобы избежать динамического изменения размера кучи во время работы.
#
# Определяйте эти значения в соответствии с вашим доступным объемом ОЗУ.
# Например, для систем с 8 ГБ ОЗУ, вы можете выделить 1 ГБ:
#
ES_JAVA_OPTS: "-Xms1g -Xmx1g"

# Включение или отключение логирования запросов (необязательно):
# http.detailed_errors.enabled: true
# logger.level: DEBUG

# Безопасность (для версий с x-pack, начиная с 6.8 и выше, если нужно включить базовую безопасность):
xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false
