stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose build
  only:
    - main

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec hotel-reservation curl --fail http://localhost:8181/api/health || exit 1
    - docker-compose down
  only:
    - main
