version: '3.7'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    networks:
      - hotel_reservation_network
    environment:
      POSTGRES_DB: Hotel_reservation_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

  hotel-reservation:
    image: kimnikituschcka913/hotel-reservation:latest
    build: .
    networks:
      - hotel_reservation_network
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/Hotel_reservation_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  grafana:
    image: kimnikituschcka913/custom-grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - hotel_reservation_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      - hotel_reservation_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grafana
      - hotel-reservation
    networks:
      - hotel_reservation_network
    restart: always

networks:
  hotel_reservation_network:
    driver: overlay

volumes:
  db:
  esdata:
    driver: local
