global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - 'tasks.my_stack_hotel-reservation'
        type: 'A'
        port: 8181
        refresh_interval: 15s
