server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  distribution:
    percentiles-histogram:
      "[http.server.requests]": true

app:
  version: 1.0.0
  start-date: ${spring.application.start-date}
springdoc:
  swagger-ui:
    oauth:
      client-id: hotel-reservation-client
      client-secret: JFbef01XNKRap00hqV8YzkGNNfD6hVdn
      datasource:
        url: jdbc:postgresql://localhost:5432/Hotel_reservation_DB
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        jpa:
          generate-ddl: false
          hibernate:
            ddl-auto: none
          show-sql: false
          properties:
            hibernate:
              format_sql: true
              dialect: org.hibernate.dialect.PostgreSQLDialect
        flyway:
          baseline-on-migrate: true
      logging:
        level:
          root: info

spring:
  profiles:
    active: test

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


