INSERT INTO hotel_amenities (hotel_id, amenity)
VALUES (1, 'BEACH'),
       (2, 'WIFI'),
       (2, 'SAUNA'),
       (2, 'POOL'),
       (2, 'BEACH'),
       (1, 'WIFI'),
       (3, 'WIFI'),
       (3, 'FREE_TOURS'),
       (3, 'FREE_BREAKFAST'),
       (3, 'BEACH'),
       (4, 'WIFI'),
       (4, 'FITNESS'),
       (4, 'FREE_PARKING'),
       (4, 'FREE_BREAKFAST')
