CREATE TABLE IF NOT EXISTS hotels
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description TEXT         NOT NULL UNIQUE,
    address     VARCHAR(200) NOT NULL,
    rating      INTEGER      NOT NULL,
    image       TEXT         NOT NULL,
    location    VARCHAR(100) NOT NULL,
    CONSTRAINT PK_HOTELS PRIMARY KEY (id)
);